config/routes.rb
Dovesibutta::Application.routes.draw do
  devise_for :users

  get "home/index"

  get "home/about"

  get "landing/index"

  root to: "home#index"

  namespace :api, :defaults => {:format => :json}  do
    namespace :v1 do
      resources :bins do
        collection do
          post 'by_location'
          post 'in_bounding_box'
        end
      end
    end
  end

  resources :bins do
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bin.rb
class Bin < ActiveRecord::Base
  mount_uploader :picture, ImageUploader
  attr_accessible :address, :city, :country, :created_by, :created_date, :description, :latitude, :longitude, :postcode, :published, :region, :picture

  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.address = geo.address
      obj.city    = geo.city
      obj.postcode= geo.postal_code
      obj.region  = geo.state
      obj.country = geo.country_code
    end
  end
  # after_validation :reverse_geocode

  validates_presence_of :picture

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :image, :description, :picturable_id, :picturable_type

  belongs_to :bin, :polymorphic => true

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/api/v1/bins_controller.rb
class Api::V1::BinsController < ApplicationController
  before_filter :check_header


  def create
    tempfile = Tempfile.new("photoupload") #a name we picked
    tempfile.binmode
    tempfile << request.body.read
    tempfile.rewind

    photo_params = params[:bin].slice(:picture, :type, :head).merge(:tempfile => tempfile)
    photo_params[:picture] = params[:bin][:picture].original_filename
    photo_params[:type] = params[:bin][:picture].content_type
    photo_params[:head] = params[:bin][:picture].headers
    photo = ActionDispatch::Http::UploadedFile.new(photo_params)
    photo.original_filename = params[:bin][:picture].original_filename

    @bin = Bin.new(params[:bin])
    @bin.picture = photo

    respond_to do |format|
      if @bin.save
        format.json { head :ok }
      else
        format.json { render :json => @bin.errors, :status => :unprocessable_entity }
      end
    end

  end

  def index
    @bins = Bin.all
    respond_to do |format|
      format.json { render :json => @bins }
    end
  end

  # Returns all bins given a specific location
  def by_location
    latitude = params[:latitude]
    longitude = params[:longitude]
    range = params[:range]  #Range in KM is specified below
    @bins = Bin.near([latitude, longitude], range, :units => :km)
    respond_to do |format|
      format.json { render :json => @bins }
    end
  end

  def in_bounding_box
    lat_sw = params[:lat_sw]
    lon_sw = params[:lon_sw]
    lat_ne = params[:lat_ne]
    lon_ne = params[:lon_ne]
    bbox = [lat_sw, lon_sw, lat_ne, lon_ne]
    @bins = Bin.within_bounding_box(bbox)
    respond_to do |format|
      format.json { render :json => @bins }
    end

  end

  private

  def check_header
    # if request.headers['DoveSiButta-Secret'].present?
    #   if request.headers['DoveSiButta-Secret'] == ENV['APP_SECRET']
    #     can_continue = true
    #   else
    #     can_continue = false
    #   end
    # else
    #   can_continue = false
    # end
    # if !can_continue
    #   respond_to do |format|
    #     format.json { render :json => {error: 'NO API KEY SPECIFIED OR API KEY NOT VALID'} }
    #   end
    # end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bins_controller.rb
class BinsController < ApplicationController
  # GET /bins
  # GET /bins.json
  def index
    @bins = Bin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bins }
    end
  end

  # GET /bins/1
  # GET /bins/1.json
  def show
    @bin = Bin.find(params[:id])
    #@picturable = @bin
    #@picture = @picturable.picture

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bin }
    end
  end

  # GET /bins/new
  # GET /bins/new.json
  def new
    @bin = Bin.new
    #@picturable = @bin
    #@note = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bin }
    end
  end

  # GET /bins/1/edit
  def edit
    @bin = Bin.find(params[:id])
  end

  # POST /bins
  # POST /bins.json
  def create
    @bin = Bin.new(params[:bin])

    respond_to do |format|
      if @bin.save
        format.html { redirect_to @bin, notice: 'Bin was successfully created.' }
        format.json { render json: @bin, status: :created, location: @bin }
      else
        format.html { render action: "new" }
        format.json { render json: @bin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bins/1
  # PUT /bins/1.json
  def update
    @bin = Bin.find(params[:id])

    respond_to do |format|
      if @bin.update_attributes(params[:bin])
        format.html { redirect_to @bin, notice: 'Bin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bins/1
  # DELETE /bins/1.json
  def destroy
    @bin = Bin.find(params[:id])
    @bin.destroy

    respond_to do |format|
      format.html { redirect_to bins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bins_helper.rb
module BinsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bins/_form.html.erb
<%= form_for @bin, :html => { :class => 'form-horizontal', :multipart => true} do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :created_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :created_date, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :created_by, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :created_by, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :postcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :postcode, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :region, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :region, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :latitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :published, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :published, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :picture, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :picture %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bins_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bins/edit.html.erb
<%- model_class = Bin -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bins/index.html.erb
<%- model_class = Bin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_date) %></th>
      <th><%= model_class.human_attribute_name(:created_by) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:postcode) %></th>
      <th><%= model_class.human_attribute_name(:region) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:published) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bins.each do |bin| %>
      <tr>
        <td><%= link_to bin.id, bin_path(bin) %></td>
        <td><%= bin.description %></td>
        <td><%= bin.created_date %></td>
        <td><%= bin.created_by %></td>
        <td><%= bin.address %></td>
        <td><%= bin.city %></td>
        <td><%= bin.postcode %></td>
        <td><%= bin.region %></td>
        <td><%= bin.country %></td>
        <td><%= bin.latitude %></td>
        <td><%= bin.longitude %></td>
        <td><%= bin.published %></td>
        <td><%=l bin.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bin_path(bin), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bin_path(bin),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bin_path,
            :class => 'btn btn-primary' %>

app/views/bins/new.html.erb
<%- model_class = Bin -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bins/show.html.erb
<%- model_class = Bin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @bin.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_date) %>:</strong></dt>
  <dd><%= @bin.created_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_by) %>:</strong></dt>
  <dd><%= @bin.created_by %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @bin.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @bin.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postcode) %>:</strong></dt>
  <dd><%= @bin.postcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:region) %>:</strong></dt>
  <dd><%= @bin.region %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @bin.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @bin.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @bin.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:published) %>:</strong></dt>
  <dd><%= @bin.published %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture) %></strong></dt>
  <dd><%= image_tag @bin.picture.url(:thumb) %></dd>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bins_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bin_path(@bin), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bin_path(@bin),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<div class="container">
  <div class="header">
    <ul class="nav nav-pills pull-right">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
    <h3 class="text-muted">Project name</h3>
  </div>

  <div class="row marketing">
    <div class="col-lg-6">
      <!-- Types -->
      <h3>Cosa butti?</h3>
      <select class="form-control" name="bin-type-select" id="bin-type-select">
        <option value="1">Plastica</option>
        <option value="2">Vetro</option>
        <option value="3">Alluminio</option>
      </select>
    </div>
    <div class="col-lg-6 pull-right">
      <h3>Dove?</h3>
      <div class="input-group">
        <input type="text" class="form-control" id="address">
            <span class="input-group-btn">
              <button class="btn btn-default" id="button-go" type="button">Go!</button>
            </span>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
  </div><!-- /.row -->

  <div class="row marketing" id="results"></div>

  <div class="row marketing">
    <!-- Map Div -->
    <div id="dsb-map"></div>
  </div>

  <div class="jumbotron">
    <h1>Jumbotron heading</h1>
    <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
    <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
  </div>

  <div class="row marketing">
    <div class="col-lg-6">
      <h4>Subheading</h4>
      <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

      <h4>Subheading</h4>
      <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

      <h4>Subheading</h4>
      <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>

    <div class="col-lg-6">
      <h4>Subheading</h4>
      <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

      <h4>Subheading</h4>
      <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

      <h4>Subheading</h4>
      <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>
  </div>

  <div class="footer">
    <p>&copy; Company 2014</p>
  </div>

</div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta http-equiv="Content-Language" content="<%= I18n.locale %>"/>
  <link rel="shortcut icon" href="favicon.ico">

  <title>Narrow Jumbotron Template for Bootstrap</title>

  <!-- Bootstrap core CSS -->
  <!--<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">-->

  <!-- Custom styles for this template -->
  <!--<link href="jumbotron-narrow.css" rel="stylesheet">-->
  <!--<%= stylesheet_link_tag 'jumbotron-narrow' %>-->

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>


<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>
  <%= yield %>
</div>
<!-- /container -->


<footer>
  <div class="container">
    <p>&copy; <%= Time.now.strftime("%Y") %> DoveSiButta </p>
  </div>
</footer>


<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= yield :scripts %>
</body>
</html>